name: Auto Ruff

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
      - release/*

jobs:
  ruff:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
        with:
          src: "."
          version: v0.0.278
          args: --config=.ruff.toml --fix
